version: '3.9'

services:
  vehicleinfoapp:
    build:
      context: ./VehicleInfoApp
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
